# Generated by Django 4.0.6 on 2022-07-08 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_inventaire_end_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Greffons',
            new_name='Greffon',
        ),
        migrations.RenameField(
            model_name='greffon',
            old_name='greffons',
            new_name='greffon',
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 21, 17, 35, 399263)),
        ),
    ]
