# Generated by Django 4.0.6 on 2022-07-10 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_greffons_greffon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='stock_future',
            new_name='stock_futur',
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 11, 26, 0, 801302)),
        ),
    ]
