# Generated by Django 4.0.6 on 2022-07-10 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_stock_future_produit_stock_futur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='espece',
            field=models.ForeignKey(default=product.models.Espece.get_default_espece, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Produits', to='product.espece'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 11, 29, 32, 608923)),
        ),
    ]
