# Generated by Django 4.0.6 on 2022-07-10 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_produit_espece_alter_inventaire_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='portegreffe',
            field=models.ForeignKey(default=product.models.PorteGreffe.get_default_portegreffe, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Produits', to='product.portegreffe'),
        ),
        migrations.AddField(
            model_name='produit',
            name='specialite',
            field=models.ForeignKey(default=product.models.Specialite.get_default_specialite, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Produits', to='product.specialite'),
        ),
        migrations.AddField(
            model_name='produit',
            name='variete',
            field=models.ForeignKey(default=product.models.Variete.get_default_variete, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Produits', to='product.variete'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 11, 29, 50, 54961)),
        ),
    ]
