# Generated by Django 4.0.6 on 2022-07-10 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_produit_portegreffe_produit_specialite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 11, 31, 3, 746014)),
        ),
    ]
